<%@ page trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="cms" uri="http://hybris.com/tld/cmstags"%>

<c:if test="${component.visible}">
	<nav class="navigation navigation--bottom js_navigation--bottom js-enquire-offcanvas-navigation" role="navigation">
		<ul class="sticky-nav-top hidden-lg hidden-md js-sticky-user-group hidden-md hidden-lg">
                <%--Dynamically generated by 'acc.navigation.js"--%>
        </ul>
		<div class="navigation__overflow">
			<ul data-trigger="#signedInUserOptionsToggle" class="nav__links nav__links--products nav__links--mobile js-userAccount-Links js-nav-collapse-body offcanvasGroup1 collapse in hidden-md hidden-lg">
                   <%--Dynamically generated by 'acc.navigation.js"--%>
           	</ul>
           	<ul class="nav__links nav__links--products js-offcanvas-links">
				<c:forEach items="${component.navigationNode.children}" var="childLevel1"> 
					<li class="auto nav__links--primary <c:if test="${not empty childLevel1.children}">nav__links--primary-has__sub js-enquire-has-sub</c:if>">
						<c:forEach items="${childLevel1.entries}" var="childlink1">
							<cms:component component="${childlink1.item}" evaluateRestriction="true" element="span" class="nav__link js_nav__link" />
						</c:forEach>
						
						<c:if test="${not empty childLevel1.children}"><span class="glyphicon  glyphicon-chevron-right hidden-md hidden-lg nav__link--drill__down js_nav__link--drill__down"></span>
							<div class="sub__navigation js_sub__navigation ${fn:escapeXml(subNavigationClass)}">
								<a class="sm-back js-enquire-sub-close hidden-md hidden-lg" href="#">Back</a>
								<div class="row">
									<c:forEach items="${childLevel1.children}" var="childLevel2"> 
										<div class="sub-navigation-section grid-container">
											<c:choose>
												<%-- if level3 is empty, show level2 entry --%>
												<c:when test="${empty childLevel2.children}">
													<c:forEach items="${childLevel2.entries}" var="childlink2">
														<cms:component component="${childlink2.item}" evaluateRestriction="true" element="div" class="grid-item" />
													</c:forEach>
												</c:when>
												<%-- if level3 is not empty, show level2 title and level3 entries --%>
												<c:otherwise>
													<c:if test="${not empty childLevel2.title}">
														<div class="title grid-item">${fn:escapeXml(childLevel2.title)}</div>
													</c:if>
													<c:forEach items="${childLevel2.children}" var="childLevel3">
														<c:forEach items="${childLevel3.entries}" var="childlink3" >
															<cms:component component="${childlink3.item}" evaluateRestriction="true" element="div" class="grid-item" />
														</c:forEach>
													</c:forEach>
												</c:otherwise>
											</c:choose>
										</div>	
									</c:forEach>  
								</div>
							</div>
						</c:if>
					</li>
				</c:forEach>
			</ul>
		</div>
	</nav>
</c:if>